language: csharp
mono:
  - latest

solution: MineLib.PGL.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore MineLib.PGL.sln

script:
  - xbuild /p:Configuration=Release MineLib.PGL.sln
  - xbuild /p:Configuration=Debug MineLib.PGL.sln

notifications:
  email:
    on_success: always
